package comunio.nas.error;

public enum ErrorType {

	TRANSFERMARKT_DE_FIND_PLAYER,
	TRANSERMARKT_DE_FIND_ABFRAGE_WEBSITE,
	GITHUB_LOADER_DATEN_FEHLEN,
	COMANALYSTICS_FEHLER_WEBSITENABFRAGE,
	ESPN_PLAYER_MAPPER,
	ESPN_PLAYER_INTEGRATOR,
	ESPN_CLUB_MAPPER,
	NONE
}
